name: ImageCopierV2
run-name: copy ${{inputs.imageId}} to ${{inputs.destImageId}}
on:
  workflow_dispatch:
    inputs:
      imageId:
        description: 'source image'
        type: string
        required: true
      destImageId:
        description: 'target image address'
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  copy:
    name: copy
    runs-on: ubuntu-latest
    steps:
      - name: copy image
        uses: cloudposse/github-action-sync-docker-repos@main
        with:
          src: ${{inputs.imageId}}
          dest: ${{inputs.destImageId}}
          dest-credentials: ${{secrets.DEST_CREDS}}