name: ImageCopier
run-name: Copy Images by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      images:
        description: 'image to be copied, multiple images must be separated with commas'
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  parse_args:
    name: parse_args
    runs-on: ubuntu-latest
    steps:
      - id: step1
        name: build matrix
        run: echo "${{inputs.images}}]" | sed 's/,/","/g;s/^/\["/;s/$/"\]/' | sed 's/^/imageIds=/'  >> "$GITHUB_OUTPUT"
    outputs:
      imageIds: ${{steps.step1.outputs.imageIds}}
  sync_image:
    name: sync_image
    runs-on: ubuntu-latest
    needs: parse_args
    strategy:
      matrix:
        imageId: ${{fromJson( needs.parse_args.outputs.imageIds )}} 
    steps:
      - name: echo
        run: echo ${{ matrix.imageId }}